/////////////////////////////////////Flow/////////////////////////////////////
# The version of flow (DO NOT CHANGE)
version: 1.0.9 TEST VERSION


# Enable "Flow"?
enabled: true


# Allow lava to be fixed?
enableLava: false
