name: Flow
main: com.github.JamesNorris.Flow.Flow
version: 1.0.7
commands:
   flow:
      description: Shows info.
      usage: Are you sure you didn't mean "/flow"?
      permission: flow.info
      permission-message: You don't have permission.
   flowfix:
      description: Fixes water.
      usage: Are you sure you didn't mean "/flowfix"?
      permission: flow.fix
      permission-message: You don't have permission.
permissions:
    flow.info:
        description: Allows user to show info.
    flow.fix:
        description: Allows user to fix water.
        default: op